# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_graphique.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1118, 814)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_load = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load.setGeometry(QtCore.QRect(160, 90, 111, 31))
        self.btn_load.setObjectName("btn_load")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(160, 150, 121, 51))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.btn_apply = QtWidgets.QPushButton(self.centralwidget)
        self.btn_apply.setGeometry(QtCore.QRect(160, 350, 111, 23))
        self.btn_apply.setObjectName("btn_apply")
        self.Btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.Btn_save.setGeometry(QtCore.QRect(680, 370, 91, 21))
        self.Btn_save.setObjectName("Btn_save")
        self.affichage_frequence = QtWidgets.QLabel(self.centralwidget)
        self.affichage_frequence.setGeometry(QtCore.QRect(680, 50, 131, 21))
        self.affichage_frequence.setObjectName("affichage_frequence")
        self.graph_widget = QtWidgets.QGraphicsView(self.centralwidget)
        self.graph_widget.setGeometry(QtCore.QRect(680, 80, 351, 281))
        self.graph_widget.setObjectName("graph_widget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 430, 931, 311))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/kd08185z/Documents/logo.png"))
        self.label.setObjectName("label")
        self.Frequence_de_coupure = QtWidgets.QLabel(self.centralwidget)
        self.Frequence_de_coupure.setGeometry(QtCore.QRect(320, 150, 61, 41))
        self.Frequence_de_coupure.setObjectName("Frequence_de_coupure")
        self.frequence_de_coupure = QtWidgets.QLabel(self.centralwidget)
        self.frequence_de_coupure.setGeometry(QtCore.QRect(320, 200, 51, 41))
        self.frequence_de_coupure.setObjectName("frequence_de_coupure")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(310, 270, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.Ordre_filtre = QtWidgets.QLabel(self.centralwidget)
        self.Ordre_filtre.setGeometry(QtCore.QRect(190, 280, 47, 13))
        self.Ordre_filtre.setObjectName("Ordre_filtre")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1118, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_load.setText(_translate("MainWindow", "Charger le signal"))
        self.comboBox.setItemText(0, _translate("MainWindow", "Filtre passe bas"))
        self.comboBox.setItemText(1, _translate("MainWindow", "Filtre passe haut "))
        self.comboBox.setItemText(2, _translate("MainWindow", "Filtre passe bande"))
        self.btn_apply.setText(_translate("MainWindow", "Appliquer le filtre"))
        self.Btn_save.setText(_translate("MainWindow", "Sauvegarder "))
        self.affichage_frequence.setText(_translate("MainWindow", "Fréquence obtenue "))
        self.Frequence_de_coupure.setText(_translate("MainWindow", "TextLabel"))
        self.frequence_de_coupure.setText(_translate("MainWindow", "TextLabel"))
        self.Ordre_filtre.setText(_translate("MainWindow", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
