# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(689, 460)

        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(500, 420, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")

        self.Bullenom = QtWidgets.QTextBrowser(Dialog)
        self.Bullenom.setGeometry(QtCore.QRect(10, 380, 281, 51))
        self.Bullenom.setObjectName("Bullenom")

        self.BulleTitre = QtWidgets.QTextBrowser(Dialog)
        self.BulleTitre.setGeometry(QtCore.QRect(10, 10, 281, 51))
        self.BulleTitre.setObjectName("BulleTitre")

        self.AffichageURL = QtWidgets.QLineEdit(Dialog)
        self.AffichageURL.setGeometry(QtCore.QRect(40, 90, 511, 20))
        self.AffichageURL.setObjectName("AffichageURL")

        self.Boutonparcourir = QtWidgets.QPushButton(Dialog)
        self.Boutonparcourir.setGeometry(QtCore.QRect(560, 90, 41, 21))
        self.Boutonparcourir.setObjectName("Boutonparcourir")

        self.Lien = QtWidgets.QLabel(Dialog)
        self.Lien.setGeometry(QtCore.QRect(20, 70, 47, 13))
        self.Lien.setObjectName("Lien")

        self.Type = QtWidgets.QLabel(Dialog)
        self.Type.setGeometry(QtCore.QRect(10, 180, 91, 16))
        self.Type.setObjectName("Type")

        self.Source = QtWidgets.QLabel(Dialog)
        self.Source.setGeometry(QtCore.QRect(10, 230, 47, 13))
        self.Source.setObjectName("Source")

        self.comboBox_Type = QtWidgets.QComboBox(Dialog)
        self.comboBox_Type.setGeometry(QtCore.QRect(50, 200, 181, 22))
        self.comboBox_Type.setObjectName("comboBox_Type")
        self.comboBox_Type.addItem("")
        self.comboBox_Type.addItem("")
        self.comboBox_Type.addItem("")
        self.comboBox_Type.addItem("")

        self.comboBox_Source = QtWidgets.QComboBox(Dialog)
        self.comboBox_Source.setGeometry(QtCore.QRect(50, 250, 181, 22))
        self.comboBox_Source.setObjectName("comboBox_Source")
        self.comboBox_Source.addItem("")
        self.comboBox_Source.addItem("")
        self.comboBox_Source.addItem("")
        self.comboBox_Source.addItem("")
        self.comboBox_Source.addItem("")

        self.retranslateUi(Dialog)

        self.buttonBox.accepted.connect(self.on_ok_clicked)
        self.buttonBox.rejected.connect(Dialog.reject)
        self.Boutonparcourir.clicked.connect(self.open_file)

        QtCore.QMetaObject.connectSlotsByName(Dialog)

    # ✅ NOUVEAU : bouton OK -> récupère les choix
    def on_ok_clicked(self):
        signal_type = self.comboBox_Type.currentText()
        source_type = self.comboBox_Source.currentText()
        url = self.AffichageURL.text()

        print("=== Données utilisateur ===")
        print("URL :", url)
        print("Type de signal :", signal_type)
        print("Source :", source_type)

    # ✅ NOUVEAU : bouton parcourir fichier
    def open_file(self):
        file_path, _ = QFileDialog.getOpenFileName(None, "Choisir un fichier")
        if file_path:
            self.AffichageURL.setText(file_path)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))

        self.Bullenom.setHtml(_translate("Dialog", "<p><b>Classe : M2-3EA</b></p><p>BOTTAZZINI ; BETTAOUI ; SILVESTRE ; GRAPIN</p>"))

        self.BulleTitre.setHtml(_translate("Dialog", "<p><b style='font-size:16pt;'>Traitement de signal</b></p><p>Partie A : Acquisition du signal</p>"))

        self.Boutonparcourir.setText(_translate("Dialog", "..."))
        self.Lien.setText(_translate("Dialog", "Lien :"))
        self.Type.setText(_translate("Dialog", "Type de Signal :"))
        self.Source.setText(_translate("Dialog", "Sources :"))

        self.comboBox_Type.setItemText(0, _translate("Dialog", "Entrer Texte"))
        self.comboBox_Type.setItemText(1, _translate("Dialog", "Audio"))
        self.comboBox_Type.setItemText(2, _translate("Dialog", "Vidéo"))
        self.comboBox_Type.setItemText(3, _translate("Dialog", "Image"))

        self.comboBox_Source.setItemText(0, _translate("Dialog", "Entrer Texte"))
        self.comboBox_Source.setItemText(1, _translate("Dialog", "Microphone"))
        self.comboBox_Source.setItemText(2, _translate("Dialog", "Capteurs"))
        self.comboBox_Source.setItemText(3, _translate("Dialog", "Caméra"))
        self.comboBox_Source.setItemText(4, _translate("Dialog", "Fichier"))

