# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(685, 460)
        self.Bullenom = QtWidgets.QTextBrowser(Dialog)
        self.Bullenom.setGeometry(QtCore.QRect(10, 380, 281, 51))
        self.Bullenom.setObjectName("Bullenom")
        self.BulleTitre = QtWidgets.QTextBrowser(Dialog)
        self.BulleTitre.setGeometry(QtCore.QRect(10, 10, 281, 51))
        self.BulleTitre.setObjectName("BulleTitre")
        self.AffichageURL = QtWidgets.QLineEdit(Dialog)
        self.AffichageURL.setGeometry(QtCore.QRect(40, 90, 511, 20))
        self.AffichageURL.setObjectName("AffichageURL")
        self.Boutonparcourir = QtWidgets.QPushButton(Dialog)
        self.Boutonparcourir.setGeometry(QtCore.QRect(560, 90, 41, 21))
        self.Boutonparcourir.setObjectName("Boutonparcourir")
        self.Lien = QtWidgets.QLabel(Dialog)
        self.Lien.setGeometry(QtCore.QRect(20, 70, 47, 13))
        self.Lien.setObjectName("Lien")
        self.Type = QtWidgets.QLabel(Dialog)
        self.Type.setGeometry(QtCore.QRect(10, 130, 91, 16))
        self.Type.setObjectName("Type")
        self.Source = QtWidgets.QLabel(Dialog)
        self.Source.setGeometry(QtCore.QRect(10, 180, 47, 13))
        self.Source.setObjectName("Source")
        self.comboBox_Type = QtWidgets.QComboBox(Dialog)
        self.comboBox_Type.setGeometry(QtCore.QRect(50, 150, 181, 22))
        self.comboBox_Type.setObjectName("comboBox_Type")
        self.comboBox_Type.addItem("")
        self.comboBox_Type.addItem("")
        self.comboBox_Type.addItem("")
        self.comboBox_Type.addItem("")
        self.comboBox_Source = QtWidgets.QComboBox(Dialog)
        self.comboBox_Source.setGeometry(QtCore.QRect(50, 200, 181, 22))
        self.comboBox_Source.setObjectName("comboBox_Source")
        self.comboBox_Source.addItem("")
        self.comboBox_Source.addItem("")
        self.comboBox_Source.addItem("")
        self.comboBox_Source.addItem("")
        self.comboBox_Source.addItem("")
        self.Exit = QtWidgets.QPushButton(Dialog)
        self.Exit.setGeometry(QtCore.QRect(580, 400, 75, 23))
        self.Exit.setObjectName("Exit")
        self.Generer = QtWidgets.QPushButton(Dialog)
        self.Generer.setGeometry(QtCore.QRect(580, 360, 75, 23))
        self.Generer.setObjectName("Generer")
        self.Bulle_taux_echantillon = QtWidgets.QLabel(Dialog)
        self.Bulle_taux_echantillon.setGeometry(QtCore.QRect(350, 140, 131, 21))
        self.Bulle_taux_echantillon.setObjectName("Bulle_taux_echantillon")
        self.Affichage_echantillon = QtWidgets.QLabel(Dialog)
        self.Affichage_echantillon.setGeometry(QtCore.QRect(480, 140, 111, 20))
        self.Affichage_echantillon.setText("")
        self.Affichage_echantillon.setObjectName("Affichage_echantillon")
        self.Bulle_enregistrement = QtWidgets.QLabel(Dialog)
        self.Bulle_enregistrement.setGeometry(QtCore.QRect(350, 170, 131, 21))
        self.Bulle_enregistrement.setObjectName("Bulle_enregistrement")
        self.Affichage_uptdate = QtWidgets.QLabel(Dialog)
        self.Affichage_uptdate.setGeometry(QtCore.QRect(490, 170, 111, 20))
        self.Affichage_uptdate.setText("")
        self.Affichage_uptdate.setObjectName("Affichage_uptdate")
        self.Affichage_nb_echantillon = QtWidgets.QLabel(Dialog)
        self.Affichage_nb_echantillon.setGeometry(QtCore.QRect(480, 200, 111, 20))
        self.Affichage_nb_echantillon.setText("")
        self.Affichage_nb_echantillon.setObjectName("Affichage_nb_echantillon")
        self.Bulle_nb_echantillon = QtWidgets.QLabel(Dialog)
        self.Bulle_nb_echantillon.setGeometry(QtCore.QRect(350, 200, 131, 21))
        self.Bulle_nb_echantillon.setObjectName("Bulle_nb_echantillon")
        self.Bulle_duree_du_signal = QtWidgets.QLabel(Dialog)
        self.Bulle_duree_du_signal.setGeometry(QtCore.QRect(350, 230, 131, 21))
        self.Bulle_duree_du_signal.setObjectName("Bulle_duree_du_signal")
        self.Affichage_duree_siganl = QtWidgets.QLabel(Dialog)
        self.Affichage_duree_siganl.setGeometry(QtCore.QRect(480, 230, 111, 20))
        self.Affichage_duree_siganl.setText("")
        self.Affichage_duree_siganl.setObjectName("Affichage_duree_siganl")
        self.Lien_2 = QtWidgets.QLabel(Dialog)
        self.Lien_2.setGeometry(QtCore.QRect(20, 310, 281, 51))
        self.Lien_2.setObjectName("Lien_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Bullenom.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600; color:#ffaa00;\">Classe : M2-3EA</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600; color:#000000;\">Groupe : </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:8pt; font-weight:600; color:#000000;\">BOTTAZZINI ; BETTAOUI ; SILVESTRE ; GRAPIN</span></p></body></html>"))
        self.BulleTitre.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:16pt; font-weight:600; color:#ffaa00;\">Traitement de signal</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:9pt; font-weight:600; color:#000000;\">Partie A : Acquisition du signal</span></p></body></html>"))
        self.Boutonparcourir.setText(_translate("Dialog", "..."))
        self.Lien.setText(_translate("Dialog", "Lien :"))
        self.Type.setText(_translate("Dialog", "Type de Signal :"))
        self.Source.setText(_translate("Dialog", "Sources :"))
        self.comboBox_Type.setItemText(0, _translate("Dialog", "Entrer Texte"))
        self.comboBox_Type.setItemText(1, _translate("Dialog", "Audio"))
        self.comboBox_Type.setItemText(2, _translate("Dialog", "Vidéo"))
        self.comboBox_Type.setItemText(3, _translate("Dialog", "Image"))
        self.comboBox_Source.setItemText(0, _translate("Dialog", "Entrer Texte"))
        self.comboBox_Source.setItemText(1, _translate("Dialog", "Microphone"))
        self.comboBox_Source.setItemText(2, _translate("Dialog", "Capteurs"))
        self.comboBox_Source.setItemText(3, _translate("Dialog", "Caméra"))
        self.comboBox_Source.setItemText(4, _translate("Dialog", "Fichier"))
        self.Exit.setText(_translate("Dialog", "Exit"))
        self.Generer.setText(_translate("Dialog", "Générer"))
        self.Bulle_taux_echantillon.setText(_translate("Dialog", "Taux d\'échantillonage : "))
        self.Bulle_enregistrement.setText(_translate("Dialog", "Derniere enregistrement :"))
        self.Bulle_nb_echantillon.setText(_translate("Dialog", "Nombre d\'échantillon : "))
        self.Bulle_duree_du_signal.setText(_translate("Dialog", "Durée du signal :"))
        self.Lien_2.setText(_translate("Dialog", "Classe : M2-3EA\n"
"Groupe : \n"
"BOTTAZZINI ; BETTAOUI ; SILVESTRE ; GRAPIN"))
